LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := STNFCDta
LOCAL_PROPRIETARY_MODULE := false
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_MODULE_OWNER := st
#LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)
LOCAL_SRC_FILES := bin/STNFCDta.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
